In [ ]:
import numpy as np

list vs Numpy - Time taken

In [ ]:
from time import process_time

Time taken By a List


In [ ]:
python_list= [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

0.0011700220000001593


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5      #np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0007012099999998966


Numpy array

In [ ]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating one dimentional arrey
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([(1,2,3,4,5),(6,7,8,9,0)])
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
b.shape

(2, 5)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholder is numpy array

In [ ]:
# creating array with all Zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# creating array with all ones

y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# creating numpay of any perticular valuse
z= np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
#creating a identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#creating a array with random no between 0 to 1

b = np.random.random((3,4))
print(b)

[[0.04466536 0.28093652 0.12777292 0.06444079]
 [0.16093179 0.82869597 0.80838174 0.22621329]
 [0.91924856 0.29324547 0.55805139 0.5858604 ]]


In [ ]:
#creating a array with random number between specific range

c =np.random.randint(10,100,(4,5))
print(c)


[[38 37 70 13 44]
 [11 85 79 30 50]
 [68 58 68 21 49]
 [67 29 34 63 91]]


In [ ]:
#creating a array with evenly spaced values --> specifying the number of values requried

d = np.linspace(10,30,6)
print(d)
type(d)

[10. 14. 18. 22. 26. 30.]


numpy.ndarray

In [ ]:
 # creating a array with evenly spaced values --> specifiying the steps
d = np.arange(10,30,6)
print(d)

[10 16 22 28]


In [ ]:
# converthing a list to numpy array
list1 = [1,2,3,4,5]

np_array = np.asarray(list1)
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [ ]:
#converthing a tuple to a numpy array

tuple1 = (1 ,2 ,3,4,5)

t_array = np.asarray(tuple1)
print(t_array)
type(t_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#analyzing a numpy array

array = np.random.randint(0,99,( 4,5))
print(array)

[[67 50 17 36 76]
 [47 79 24 71 53]
 [89  5 69 42 40]
 [64 38 66 53 74]]


In [ ]:
print(array.shape)

(4, 5)


In [ ]:
array.size

20

In [ ]:
array.ndim

2

In [ ]:
print(array.dtype)

int64


In [ ]:
#mathematical opration on np arrays

a = np.random.randint(0,99,( 4,5))
b = np.random.randint(0,99,( 4,5))
print(a)
print(b)

[[93  0 51 89 51]
 [83 73  4 18 12]
 [40 71 16 64  8]
 [96 14 40 65 67]]
[[56 87 45 26 35]
 [71 31 57  5 10]
 [ 5 62 23 93 14]
 [31 38 68 59 11]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[149  87  96 115  86]
 [154 104  61  23  22]
 [ 45 133  39 157  22]
 [127  52 108 124  78]]
[[ 37 -87   6  63  16]
 [ 12  42 -53  13   2]
 [ 35   9  -7 -29  -6]
 [ 65 -24 -28   6  56]]
[[5208    0 2295 2314 1785]
 [5893 2263  228   90  120]
 [ 200 4402  368 5952  112]
 [2976  532 2720 3835  737]]
[[1.66071429 0.         1.13333333 3.42307692 1.45714286]
 [1.16901408 2.35483871 0.07017544 3.6        1.2       ]
 [8.         1.14516129 0.69565217 0.68817204 0.57142857]
 [3.09677419 0.36842105 0.58823529 1.10169492 6.09090909]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[149  87  96 115  86]
 [154 104  61  23  22]
 [ 45 133  39 157  22]
 [127  52 108 124  78]]
[[ 37 -87   6  63  16]
 [ 12  42 -53  13   2]
 [ 35   9  -7 -29  -6]
 [ 65 -24 -28   6  56]]
[[5208    0 2295 2314 1785]
 [5893 2263  228   90  120]
 [ 200 4402  368 5952  112]
 [2976  532 2720 3835  737]]
[[1.66071429 0.         1.13333333 3.42307692 1.45714286]
 [1.16901408 2.35483871 0.07017544 3.6        1.2       ]
 [8.         1.14516129 0.69565217 0.68817204 0.57142857]
 [3.09677419 0.36842105 0.58823529 1.10169492 6.09090909]]


In [ ]:
#manuplation of an array
array = np.random.randint(0,100,(4,5))
print(array)
array.shape

[[44 77 52 44 30]
 [65 72 59 71 94]
 [23 45 67 34 91]
 [28  9 95 36 80]]


(4, 5)

In [ ]:
#trainspose
trans = np.transpose(array)
print(trans)
trans.shape

[[44 65 23 28]
 [77 72 45  9]
 [52 59 67 95]
 [44 71 34 36]
 [30 94 91 80]]


(5, 4)

In [ ]:
# OR

trans2 = array.T
print(trans2)
trans2.shape


[[44 65 23 28]
 [77 72 45  9]
 [52 59 67 95]
 [44 71 34 36]
 [30 94 91 80]]


(5, 4)

In [ ]:
#reshapeing a array
array2 = np.random.randint(0,100,(4,5))
print(array2)
array2.shape

[[54 59 41 17 77]
 [97 66 20 71 28]
 [75 38 62 92 70]
 [ 4 49 44 23  6]]


(4, 5)

In [ ]:
array3 = np.reshape(array2,(5,4))
print(array3)
array3.shape

[[54 59 41 17]
 [77 97 66 20]
 [71 28 75 38]
 [62 92 70  4]
 [49 44 23  6]]


(5, 4)